spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: Indhu@#29cvraja
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
application:
  security:
    jwt:
      secret-key: "463acbfe899899b42511b4f404593cf8118b194bc4306826af847c8babdaa9e9"
